name: Release

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest
    secrets: ["PSGALLERY_API_KEY"]

    steps:
    - uses: actions/checkout@v1
    - name: Publish
      run: |
        pwsh -Command "Publish-Module -Path ./PowerArubaCP -NuGetApiKey $Env:PSGALLERY_API_KEY"
